parameters:
    database_driver: pdo_mysql
    database_host: db507974253.db.1and1.com
    database_port: null
    database_name: db507974253
    database_user: dbo507974253
    database_password: dbo499966472
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: es
    secret: 95d0639e3b647d86848a647edbe93795d9dce409
    database_path: null
